feat: Add the Cluster Autoscaler
CloudGeometry/cg-devx-core pull request #34
Opened 2023-12-22 11:53 UTC by aakilin

- fix sync-wave inside the application folder
- add IAM module "cluster_autoscaler_irsa_role"
- move the cluster-autoscaler path to kube-system
- inner wave shouldn’t be 30th - make sense to set it 0
- clustername inside the values should be a tokenized by `<PRIMARY_CLUSTER_NAME>`
- aws-region should be tokenized by `<CLOUD_REGION>`
- cloud-provider should be tokenized by `<CLOUD_PROVIDER>`
- service-account should be tokenized by SERVICE_ACCOUNT - create the new one
`<K8S_ROLE_MAPPING>: “<CLUSTER_AUTOSCALER_IAM_ROLE_RN>”`
- add the output cluster_autoscaler_role with `value       = module.hosting-provider.cluster_autoscaler_irsa_role`
- add `p.parameters["<CLUSTER_AUTOSCALER_IAM_ROLE_RN>"] = hp_out["cluster_autoscaler_role"]`
- add the `cluster_autoscaler_irsa_role` to the terraform `cloud_aws` module outputs

2024-02-02 11:14 UTC, sergs-pci requested changes

2024-02-02 11:14 UTC, sergs-pci commented on tools/cli/services/cloud/aws/aws_manager.py
> +    def create_iac_pr_automation_config_snippet(self):
Looks wrong

2024-02-02 11:14 UTC, sergs-pci commented on tools/cli/services/cloud/azure/azure_manager.py
> -    def create_autoscaler_snippet(self, cluster_name: str, node_groups=[]):
the same as above, looks like with this conflict resolving you are deleting necessary changes

2024-02-02 18:01 UTC, sergs-pci requested changes

2024-02-02 18:01 UTC, sergs-pci commented on platform/gitops-pipelines/delivery/clusters/cc-cluster/core-services/components/kube-system/cluster-autoscaler/application.yaml
I expected more compact file here

2024-02-02 18:01 UTC, sergs-pci commented on platform/gitops-pipelines/delivery/clusters/cc-cluster/core-services/components/kube-system/cluster-autoscaler/application.yaml
> +        podLabels: {}
looks like important parameter missed here

2024-02-02 18:01 UTC, sergs-pci commented on platform/terraform/modules/cloud_azure/service_accounts.tf
> +  resource_group_name  = azurerm_resource_group.rg.name
you missed resource_group_location attribute here

2024-02-02 18:01 UTC, sergs-pci commented on tools/cli/services/cloud/azure/azure_manager.py
>      def create_iac_pr_automation_config_snippet(self):
looks wrong that you remain these lines

2024-02-02 23:37 UTC, sergs-pci submitted a review, later dismissed

2024-02-12 14:04 UTC, all4code requested changes

2024-02-12 14:04 UTC, all4code commented on platform/terraform/modules/cloud_azure/main.tf
> +  enable_native_auto_scaling = false
Please move to vars with default value = false

2024-02-12 14:04 UTC, all4code commented on platform/terraform/modules/cloud_azure/service_accounts.tf
>  }
Please pay attention to formatting.

2024-02-12 14:04 UTC, all4code commented on tools/cli/services/cloud/azure/azure_manager.py
> +        self.__azure_sdk = AzureSdk(subscription_id, location)
Should use name with one underscore.

2024-02-12 14:27 UTC, all4code approved these changes

2024-02-12 14:58 UTC, sergs-pci approved these changes

2024-02-12 15:47 UTC, merged