Feature/vcs gitlab module
CloudGeometry/cg-devx-core pull request #38
Opened 2024-01-19 14:11 UTC by alysenko-bekitzur

### Requirements

* Filling this template is required. Pull request without enough information to be reviewed may be closed

### Description of the Change

### Alternate Designs

### Benefits

### Possible Drawbacks

### Verification Process

### Applicable Issues

2024-01-30 12:39 UTC, sergs-pci requested changes

2024-01-30 12:39 UTC, sergs-pci commented on platform/terraform/modules/vcs_gitlab/repository/main.tf
> +provider "gitlab" {
Suggest to remove this block. With it I'm receiving 

> │ Warning: Redundant empty provider block
> │
> │   on ../modules/vcs_gitlab/repository/main.tf line 14:
> │   14: provider "gitlab" {
> │
> │ Earlier versions of Terraform used empty provider blocks ("proxy provider configurations") for child modules to declare their need to be passed a provider configuration by their callers. That approach was ambiguous and is
> │ now deprecated.
> │
> │ If you control this module, you can migrate to the new declaration syntax by removing all of the empty provider "gitlab" blocks and then adding or updating an entry like the following to the required_providers block of
> │ module.vcs.module.gitops-repo:
> │     gitlab = {
> │       source = "gitlabhq/gitlab"
> │     }
> │
> │ (and one more similar warning elsewhere)

2024-01-30 12:39 UTC, sergs-pci commented on platform/terraform/modules/vcs_gitlab/repository/main.tf
> +  push_access_level = "no one"
Afraid that can block some automation that we had. Need additionally discuss this

2024-01-30 12:39 UTC, sergs-pci commented on platform/terraform/modules/vcs_gitlab/repository/team.tf
> +data "gitlab_current_user" "current_user" {}
Why do we need to have this?

2024-01-30 12:39 UTC, sergs-pci commented on platform/terraform/modules/vcs_gitlab/repository/team.tf
> +resource "gitlab_group" "owners" {
Where is the gitlab_project_share_group resource for the owner group?

2024-01-30 12:39 UTC, sergs-pci commented on platform/terraform/modules/vcs_gitlab/repository/variable.tf
> +  default = true
Not sure that TRUE is suitable for the default value here. Let's discuss.

2024-02-01 00:09 UTC, alysenko-bekitzur commented on platform/terraform/modules/vcs_gitlab/repository/team.tf
> +data "gitlab_current_user" "current_user" {}
Removed

2024-02-01 00:10 UTC, alysenko-bekitzur commented on platform/terraform/modules/vcs_gitlab/repository/team.tf
> +resource "gitlab_group" "owners" {
Added

2024-02-01 00:10 UTC, alysenko-bekitzur commented on platform/terraform/modules/vcs_gitlab/repository/variable.tf
> +  default = true
Set default to false

2024-02-01 11:02 UTC, sergs-pci approved these changes

2024-02-02 12:36 UTC, sergs-pci submitted a review, later dismissed

2024-02-12 15:23 UTC, all4code requested changes

2024-02-12 15:23 UTC, all4code commented on tools/cli/services/vcs/github/github_manager.py
> +              version = "~> 5.42.0"
Please move version to constants (common/const/const.py)

2024-02-12 15:23 UTC, all4code commented on tools/cli/services/vcs/gitlab/gitlab_manager.py
> +              version = "16.7.0"
Please move version to constants (common/const/const.py)

2024-02-21 14:33 UTC, all4code approved these changes

2024-02-21 15:00 UTC, sergs-pci approved these changes

2024-02-22 12:43 UTC, merged