feat: Argo Workflows RBAC definitions and CWFTs
CloudGeometry/cg-devx-core pull request #46
Opened 2024-02-05 08:08 UTC by vtsarfin-cg

### Description of the Change

 - major changes and version upgrade of Argo Workflows application.yaml
 - Cluster Workflow Templates instead of Workflow Templates
 - Service Accounts definitions for RBAC

### Alternate Designs

### Benefits

### Possible Drawbacks

### Verification Process

### Applicable Issues

2024-02-06 10:13 UTC, sergs-pci requested changes

2024-02-06 10:13 UTC, sergs-pci commented on platform/gitops-pipelines/delivery/clusters/cc-cluster/core-services/components/argo-workflows/wait.yaml
> +          image: registry.hub.docker.com/bitnami/kubectl:1.27.4
please return back the parameter

2024-02-06 10:13 UTC, sergs-pci commented on platform/gitops-pipelines/delivery/clusters/cc-cluster/core-services/components/argo-workflows/workflow-templates/promote-wft.yaml
> +            git config --global user.name  "cgdevx-bot"
please return back the parameters

2024-02-06 10:13 UTC, sergs-pci commented on platform/gitops-pipelines/delivery/clusters/cc-cluster/core-services/components/argo-workflows/workflow-templates/version-changer-wft.yaml
> +            git config --global user.name  "cgdevx-bot"
please return back the parameters

2024-02-06 10:13 UTC, sergs-pci commented on platform/gitops-pipelines/delivery/clusters/cc-cluster/core-services/components/argo-workflows/wait.yaml
> +          image: registry.hub.docker.com/bitnami/kubectl:1.27.4
please return back the parameter

2024-02-06 10:13 UTC, sergs-pci commented on platform/gitops-pipelines/delivery/clusters/cc-cluster/core-services/components/argo-workflows/application.yaml
> -          - --secure
need to discuss this

2024-02-06 10:13 UTC, sergs-pci commented on platform/gitops-pipelines/delivery/clusters/cc-cluster/core-services/components/argo-workflows/application.yaml
> +            globallevel: '6'
It looks like it was for debugging purposes. Not sure that it is necessary to remain by default.

2024-02-07 07:03 UTC, vtsarfin-cg commented on platform/gitops-pipelines/delivery/clusters/cc-cluster/core-services/components/argo-workflows/wait.yaml
> +          image: registry.hub.docker.com/bitnami/kubectl:1.27.4
fixed, thank you.

2024-02-07 07:07 UTC, vtsarfin-cg commented on platform/gitops-pipelines/delivery/clusters/cc-cluster/core-services/components/argo-workflows/workflow-templates/promote-wft.yaml
> +            git config --global user.name  "cgdevx-bot"
Actually we do not need workflow-templates anymore, but it's better to leave it for the backward compatibility.
So I put these parameters back. 
Fixed, thank you.

2024-02-07 07:12 UTC, vtsarfin-cg commented on platform/gitops-pipelines/delivery/clusters/cc-cluster/core-services/components/argo-workflows/workflow-templates/version-changer-wft.yaml
> +            git config --global user.name  "cgdevx-bot"
Fixed, thank you.

2024-02-07 07:18 UTC, vtsarfin-cg commented on platform/gitops-pipelines/delivery/clusters/cc-cluster/core-services/components/argo-workflows/application.yaml
> -          - --secure
There is a special parameter in values to turn server "secure" — secure, false by default. We don't need to turn it on because of using ingress to terminate ssl (we discussed it on a last sync). That's why we do not need it as command line key for the argo server.

2024-02-07 07:18 UTC, vtsarfin-cg commented on platform/gitops-pipelines/delivery/clusters/cc-cluster/core-services/components/argo-workflows/application.yaml
> +            globallevel: '6'
Agree. I can always put it back on deployed instance.
Fixed, thank you.

2024-02-07 11:21 UTC, sergs-pci approved these changes

2024-02-07 12:00 UTC, sergs-pci requested changes
need add main proxy robot & workload specific push robot functionality to core_module terraform module

2024-02-09 12:19 UTC, sergs-pci approved these changes

2024-02-09 12:20 UTC, sergs-pci commented
> need add main proxy robot & workload specific push robot functionality to core_module terraform module

realized in another PR #47

2024-02-12 15:04 UTC, sergs-pci submitted a review, later dismissed

2024-02-14 12:29 UTC, sergs-pci approved these changes

2024-02-14 12:30 UTC, merged