Introduce KEDA and VPA
CloudGeometry/cg-devx-core pull request #92
Opened 2024-06-25 21:31 UTC by all4code

Introduce [KEDA](https://keda.sh/) and [Vertical Pod Autoscaler (VPA)](https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler). KEDA also comes with Grafana dashboard. Both could be installed using optional services flags. 
Example of VPA + HPA/KEDA support is added to CNASK workload template.

2024-06-26 15:55 UTC, sergs-pci requested changes

2024-06-26 15:55 UTC, sergs-pci commented on platform/gitops-pipelines/delivery/clusters/cc-cluster/core-services/components/monitoring/kube-prometheus-stack.yaml
> +                url: https://raw.githubusercontent.com/kedacore/keda/main/config/grafana/keda-dashboard.json
Is it okay to add a dead dashboard for cases when the Keda feature is disabled, or do we need to transform this to the snippet?

2024-06-26 15:55 UTC, sergs-pci commented on platform/gitops-pipelines/delivery/clusters/cc-cluster/core-services/180-vpa.yaml
> +    namespace: kube-system
Can we move the VPA to another dedicated namespace? I prefer to keep the kube-system namespace only with default vanilla k8s components.

2024-06-26 15:55 UTC, sergs-pci commented on platform/gitops-pipelines/delivery/clusters/cc-cluster/core-services/components/kube-system/vpa/kustomization.yaml
> +namespace: kube-system
it is not necessary here, because must be inherited from parent argocd application

2024-06-26 15:55 UTC, sergs-pci commented on platform/gitops-pipelines/delivery/clusters/cc-cluster/core-services/components/kube-system/vpa/vpa-admission-controller-deployment.yaml
> +  namespace: kube-system
it is not necessary here, because must be inherited from parent argocd application

2024-06-26 16:59 UTC, all4code commented on platform/gitops-pipelines/delivery/clusters/cc-cluster/core-services/components/monitoring/kube-prometheus-stack.yaml
> +                url: https://raw.githubusercontent.com/kedacore/keda/main/config/grafana/keda-dashboard.json
I was expecting this question actually. IMO we could have it even if we don't install KEDA by default. We also have other dashboards that are optional.
I could convert it into fragment and generate in code if you'd like. IMHO it's fine as it is.

2024-06-26 17:02 UTC, all4code commented on platform/gitops-pipelines/delivery/clusters/cc-cluster/core-services/180-vpa.yaml
> +    namespace: kube-system
How about moving both KEDA and VPA to dedicated namespace, eg "scalers". Maybe `cluster-autoscaler` too? Or have dedicated namespace for VPA, similar to KEDA, so they are both in their own namespaces?

2024-06-26 19:44 UTC, sergs-pci commented on platform/gitops-pipelines/delivery/clusters/cc-cluster/core-services/components/monitoring/kube-prometheus-stack.yaml
> +                url: https://raw.githubusercontent.com/kedacore/keda/main/config/grafana/keda-dashboard.json
I'm fine with this, let's remain as is.

2024-06-27 15:39 UTC, sergs-pci commented on platform/gitops-pipelines/delivery/clusters/cc-cluster/core-services/180-vpa.yaml
> +    namespace: kube-system
I prefer to have each component in a unique namespace, it is much easier to control roles and service accounts, isolate with network policy when we will implement network isolation, etc.

2024-07-01 11:40 UTC, sergs-pci approved these changes

2024-07-01 11:40 UTC, sergs-pci commented on platform/gitops-pipelines/delivery/clusters/cc-cluster/core-services/components/scalers/vpa/self-signed-cert.yaml
> +    - vpa-webhook.kube-system.svc
I think need to rename the DNS name from vpa-webhook.kube-system.svc to vpa-webhook.keda.svc here

2024-07-02 13:21 UTC, merged